version: "3.0"

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app:ro
    depends_on :
      - postgres
  
  postgres:
    image: postgres
    container_name: postgresdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
